
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"    
      - "15672:15672" 
    networks:
      - nest-network
  
  inventory-db:
    image: postgres:postgres:15
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - nest-network
    volumes:
      - inventory-db-data:/var/lib/postgresql/data
  order-db:
    image: postgres:postgres:15
    container_name: order-db
    environment:
      POSTGRES_DB: order
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - nest-network
    volumes:
      - order-db-data:/var/lib/postgresql/data

  payment-db:
    image: postgres:15
    container_name: payment-db
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    networks:
      - nest-network
    volumes:
      - payment-db-data:/var/lib/postgresql/data
  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"
    networks:
      - nest-network
    volumes:
      - user-db-data:/var/lib/postgresql/data

  api-gateway-dev:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    container_name: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - inventory-service-dev
      - order-service-dev
      - payment-service-dev
      - user-management-service-dev
    networks:
      - nest-network
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672

  inventory-service-dev:
    build:
      context: ./inventroy
    container_name: inventory-service
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq
      - inventory-db
    environment:
      - DB_HOST=inventory-db
      - DB_PORT=5432
      - DB_NAME=inventory
      - DB_USER=postgres
      - DB_PASS=password
      - RABBITMQ_URL=amqp://rabbitmq:5672

    networks:
      - nest-network
     
  order-service-dev:
    build:
      context: ./order
    container_name: order-service
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq
      - order-db
    networks:
      - nest-network
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - DB_HOST=order-db
      - DB_PORT=5433
      - DB_NAME=order
      - DB_USER=postgres
      - DB_PASS=password

  payment-service-dev:
    build:
      context: ./payement
    container_name: payement-service
    ports:
      - "3005:3005"
    depends_on:
      - rabbitmq
      - payment-db
    networks:
      - nest-network
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - DB_HOST=payment-db
      - DB_PORT=5435
      - DB_NAME=payments
      - DB_USER=postgres
      - DB_PASS=password
  user-management-service-dev:
    build:
      context: ./user-management
    container_name: user-management-service
    ports:
      - "3007:3007"
    volumes:
      - ./api-gateway:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - rabbitmq
      - user-db
    networks:
      - nest-network
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - DB_HOST=user-db
      - DB_PORT=5436
      - DB_NAME=users
      - DB_USER=postgres
      - DB_PASS=password

networks:
  nest-network:
    driver: bridge




