version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - nest-network

  inventory-db:
    image: postgres:15
    container_name: inventory-db
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - nest-network
    volumes:
      - inventory-db-data:/var/lib/postgresql/data

  order-db:
    image: postgres:15
    container_name: order-db
    environment:
      POSTGRES_DB: order
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    networks:
      - nest-network
    volumes:
      - order-db-data:/var/lib/postgresql/data

  payment-db:
    image: postgres:15
    container_name: payment-db
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    networks:
      - nest-network
    volumes:
      - payment-db-data:/var/lib/postgresql/data

  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5436:5432"
    networks:
      - nest-network
    volumes:
      - user-db-data:/var/lib/postgresql/data

  api-gateway-dev:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    container_name: api-gateway
    ports:
      - "3001:3001"
    volumes:
      - ./api-gateway:/usr/src/app
    depends_on:
      - inventory-service-dev
      - order-service-dev
      - payment-service-dev
      - user-management-service-dev
    networks:
      - nest-network
    environment:
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - PORT 3001

  inventory-service-dev:
    build:
      context: ./inventroy
      dockerfile: Dockerfile.dev
    container_name: inventory-service
    ports:
      - "3002:3002"
    volumes:
      - ./inventroy:/usr/src/app
    depends_on:
      - rabbitmq
      - inventory-db
    networks:
      - nest-network
    environment:
      - DB_HOST=inventory-db
      - DB_PORT=5432
      - DB_NAME=inventory
      - DB_USER=postgres
      - DB_PASS=password
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - PORT 3002

  order-service-dev:
    build:
      context: ./order
      dockerfile: Dockerfile.dev
    container_name: order-service
    ports:
      - "3005:3005"
    volumes:
      - ./order:/usr/src/app
    depends_on:
      - rabbitmq
      - order-db
    networks:
      - nest-network
    environment:
      - DB_HOST=order-db
      - DB_PORT=5432
      - DB_NAME=order
      - DB_USER=postgres
      - DB_PASS=password
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - PORT 3005

  payment-service-dev:
    build:
      context: ./payement
      dockerfile: Dockerfile.dev
    container_name: payement-service
    ports:
      - "3003:3003"
    volumes:
      - ./payement:/usr/src/app
    depends_on:
      - rabbitmq
      - payment-db
    networks:
      - nest-network
    environment:
      - DB_HOST=payment-db
      - DB_PORT=5432
      - DB_NAME=payments
      - DB_USER=postgres
      - DB_PASS=password
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - PORT 3003

  user-management-service-dev:
    build:
      context: ./user-management
      dockerfile: Dockerfile.dev
    container_name: user-management-service
    ports:
      - "3004:3004"
    volumes:
      - ./user-management:/usr/src/app
    depends_on:
      - rabbitmq
      - user-db
    networks:
      - nest-network
    environment:
      - DB_HOST=user-db
      - DB_PORT=5432
      - DB_NAME=users
      - DB_USER=postgres
      - DB_PASS=password
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - PORT 3004
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecret
    ports:
      - "8081:80"
    depends_on:
      - user-db
    networks:
      - nest-network

volumes:
  inventory-db-data:
  order-db-data:
  payment-db-data:
  user-db-data:

networks:
  nest-network:
    driver: bridge
