# Dockerfile.dev

FROM node:20-alpine

# Set working directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN yarn install

# Copy source files
COPY . .

# Expose port
EXPOSE 3001

VOLUME [ "/data" ]

# Start NestJS in watch mode
CMD ["npm", "run", "start:dev"]
