# Dockerfile.dev

FROM node:20-alpine

# Set working directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json yarn.lock ./
RUN yarn install

# Copy source files
COPY . .

# Expose port
EXPOSE 3004

VOLUME [ "/data" ]

# Start NestJS in watch mode
CMD ["yarn", "run", "start:dev"]
